dist: trusty
sudo: false
language: node_js
node_js:
- 12
after_success:
- "./node_modules/.bin/codecov"
deploy:
  provider: npm
  email: opensource@wayfair.com
  api_key:
    secure: bZpDVDvp/dkmhdom0pCIJ98yDMJyhKhPSRgoD5pcDQvSlGaap9tjQncfh4mJSmmDL5XLgx7aqP6pqXwxEj6TYDXyRewcCFVDWBv8enqFLWnjfx7T2CBVO99w0j29jldGACNVAwW1BPKsBah11AfrjF+m33m49ox0robDmXLo5cI2cFvEUtXgUo6zbdnHEVjqbmz9nx8IOZYi5/YWE0Z6/t/Bzi3lCgnzGr5mZntGrY58VGLgKR9HpMuhbiD57gtXoQoKns6TsKypxSza3hRnE+VvWK0JtYNTJwQixgoYh/tpTVhnqa9+m+opPhQkDSjpAL5Toi6hBoxqoGBlyiKSgkNIjQrga8K1zaG7/a4ljO2nNaPugos7hOAs+DcQB+u8dKaGJb9dhizGhlXoPypcvH+CyhL0KKvZ/gWQNMvZVT6O6iYfh2KzHw/Gu4oAmBUV8CoQTtfF3mOuW3fbEETF0rTpGPgpOTaQXK30NAiJcBLD2no4JmMUjzNKYyiiwprCt2rEnWnsrNrP44PjiXfvnCBywrE6ee3EZocJ01nyAyeGCaftkFwZ2Eq+1CBI2N/e888UVodrOErWqgkNr/U3uiCJVtBVzrMQM096R9FkcsPD0L2Em6Qfl4bg3DkPhIksdPXl2/uQ+q9YGrQhGXYS9VelRv1O+TV3p2kGMK+oL1M=
  on:
    tags: true
    repo: wayfair/dociql
    branch: master
