introspection: https://api.staging365.net/v1.0/graphql

servers:
  - url: https://api.staging365.net/v1.0/graphql
    description: Development
  - url: https://api.page365.com/v1.0/graphql
    description: Production

info:
  title: Page365 API
  description: |
    Welcome to Page365 API. Page365 allow access to merchant information on Page365 ecosystem by external software (API) for the greater service and merchant convenience.

    This API  use GraphQL as standard protocol. Implement by follow document below.

domains:
  - name: Registation
    description: |
      Before using API, you need to register your app profile and get approve by Page365 and we will send you SECRET_KEY for using in authentication process as flowchart below.
    diagram_image_name: registration.png
    usecases:
    - name: Create profile
      description: Create profile for using in authentication process and grant permission to fetch merchant information. These argument some will be display to merchant for notify them that your integration is available such as name, some will be use for report and notify an update (deprecate API) such as phone and email
      query: mutation.createPublicApp
  - name: Authentication
    description: |
      After profile approved, Page365 will send you SECRET_KEY which will be use as part of access token creating process. Access token is needed for every request as an identifier and each merchant will use difference unique access token even from the same profile.
      
      In access token creation process you will need 2 parameters (SECRET_KEY, MERCHANT_TOKEN) you can find MERCHANT_TOKEN from each merchant directly and
      
      PROVIDER NEEDS TO KEEP MERCHANT_TOKEN IN PRIVATE AND NOT ALLOW TO PUBLIC TOKEN TO OTHER
    diagram_image_name: authentication.png
    usecases:
    - name: Generate access token
      description: Generate access token for using in identification when calling API
      query: query.generateToken
  - name: Product
    description: Fetch merchant product information
    usecases:
    - name: Fetch products
      description: Fetch all product information owned by merchant
      query: query.products
    - name: Fetch product
      description: Fetch product information by id
      query: query.product
  - name: Product Category
    description: Fetch merchant product category information
    usecases:
    - name: Fetch product categories
      description: Fetch all product category information owned by merchant
      query: query.productCategories
    - name: Fetch product category
      description: Fetch product category information by id
      query: query.productCategory

schema:
  except: [
    'Account', 'Home', 'User', 'Plan', 'PageInfo', 'Order', 'OrderItem',
    # 'Account', 'Boolean', 'Customer', 'Float', 'ID', 'Int', 'ISO8601DateTime',
    # 'ProductCategoryConnection', 'ProductCategoryEdge', 'ProductConnection', 'ProductEdge',
    # 'ProductVariantConnection', 'ProductVariantEdge'
  ]