introspection: https://api.staging365.net/v1.0/graphql

servers:
  - url: https://api.staging365.net/v1.0/graphql
    description: Development
  - url: https://api.page365.com/v1.0/graphql
    description: Production

info:
  title: Page365 API
  description: |
    Welcome to Page365 API. This standard allows you to become a supported partner, manage order and inventory for over 300,000 merchants on the Page365 platform.

    API is implemented in standard GraphQL protocol, and we do not yet have language libraries available. You can view examples for how to invoke the requests in the dark area to the right.

domains:
  - name: Registation
    description: |
      Create your app profile and use it as main account to communicate with Page365.
      After your create profile request send, Please contact us for approvng your profile and we will send you a SECRET_KEY.
      Which your software will use it as credential for granting merchant token
    diagram_image_name: registration.png
    usecases:
    - name: Create profile
      description: Create a profile which you will use to communicate with Page365
      query: mutation.createPublicApp
  - name: Authentication
    description: |
      By query merchant information you need to grant access token which unique per merchant (1-to-1).
    diagram_image_name: authentication.png
    usecases:
    - name: Generate access token
      description: Generate access token for accessing merchant information
      query: query.generateToken
  - name: Product
    description: Fetch merchant product information
    usecases:
    - name: Fetch products
      description: All product owned by mechant
      query: query.products
    - name: Fetch product
      description: Eligible product owned by mechant
      query: query.product
  - name: Product Category
    description: Fetch merchant product category information
    usecases:
    - name: Fetch product categories
      description: All product category owned by mechant
      query: query.productCategories
    - name: Fetch product category
      description: Eligible product category owned by mechant
      query: query.productCategory

schema:
  except: [
    'Account', 'Home', 'User', 'Plan', 'PageInfo', 'Order', 'OrderItem',
    # 'Account', 'Boolean', 'Customer', 'Float', 'ID', 'Int', 'ISO8601DateTime',
    # 'ProductCategoryConnection', 'ProductCategoryEdge', 'ProductConnection', 'ProductEdge',
    # 'ProductVariantConnection', 'ProductVariantEdge'
  ]